services:

  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
